stages:
  - check
  - unittest
  - run

default:
  image: python:2.7-slim

syntax-check:
  stage: check
  script:
    - pip install pylint
    - pylint *.py --confidence=INFERENCE
  allow_failure: true
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

unit-test:
  stage: unittest
  script:
    - python unittest_handle404.py
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

run_script:
  stage: run
  before_script:
    - echo $MAC_ADDR
  script:
    - python macapi.py $API_KEY $MAC_ADDR
  only:
    refs:
      - develop
      - master
  except:
    changes:
      - "README.md"
