stages:
  - check
  - unittest
  - run

default:
  image: python:2.7-slim

syntax-check:
  stage: check
  script:
    - pip install pylint
    - pylint macapi.py --confidence=INFERENCE
  only:
    refs:
      - develop
      - master
  except:
    changes:
      - "README.md"

unit-test:
  stage: unittest
  script:
    - python unittest_handle404.py
  only:
    refs:
      - develop
      - master
  except:
    changes:
      - "README.md"

run_script:
  stage: run
  script:
    - python macapi.py $API_KEY 70:81:05:d2:25:0d
  only:
    refs:
      - develop
      - master
  except:
    changes:
      - "README.md"
