stages:
  - check
  - unittest
  - run
  - build

default:
  image: python:2.7-slim

syntax_check:
  stage: check
  script:
    - pip install pylint
    - pylint *.py --confidence=INFERENCE
  allow_failure: true
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

unit_test:
  stage: unittest
  script:
    - python unittest_handle404.py
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

run_script:
  stage: run
  before_script:
    - echo $MAC_ADDR
  script:
    - python macapi.py $API_KEY $MAC_ADDR
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"

build_docker_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/lok.bruce/query-mac-api .
    - docker push registry.gitlab.com/lok.bruce/query-mac-api:latest
  only:
    refs:
      - develop
  except:
    changes:
      - "README.md"
